### PR TITLE
added initial version of German translation

### PR DESCRIPTION
**Pull request by heuchi**
I've started adding a German translation. There is still a bunch of things missing, but I wanted to share what I already have, and see if you have any comments so far.

Some things I noticed:
<ol><li>The Italian translation seems to be broken. When I try so select it on first run, Raptor crashes immediately. If I try to select it later in Preferences, the pref window disappears, and won't come back. I'd be interested to hear, if you can confirm this problem.</li>
<li>Some of the buttons don't seem to be translatable (like draw, resign and abort buttons while playing). Also some buttons in the preferences window (like 'Browse' or 'Apply') seem to not translate.</li>
<li>Raptor doesn't compile successfully (neither using ant, nor eclipse) on my linux system without changing line 13 in build.xml to set swtEnv to Linux_x86_64_GTK2.</li></ol>

### CODE REVIEW

**Comment by cday-fics** [comment]
I will take a look at the Italian translation and see what is broken. Also thanks for pointing out the buttons that don't have translations. I will look into adding those. 

I am really busy right now so it might take me a week or 2 to merge in your changes along with these fixes but I will get around to it.

**Comment by heuchi** [comment]
Alright, no hurry. Meanwhile, I'll see if I can add some more translations and update the PR.

**Comment by cday-fics** [comment]
Next weekend I will take a close look at the messages that are broken and add them to the en properties so they are easy to fix. I also invited you to be a committer.

**Comment by cday-fics** [comment]
I see whats going on with the buttons now. The descriptions have translations but the names do not. So the tooltips work, but what is shown on the screen is always english. It turns out there are ~200 of these so I am going to look at writing a tool to add them in.

**Comment by cday-fics** [comment]
I tried to reproduce your 1 but couldn't. Maybe it is linux specific I am not sure.

Also on your 3, yeah you have to change that to match your environment. I have it setup to build and run in mac osx right now.

**Comment by heuchi** [comment]
1 has been fixed by https://github.com/Raptor-Fics-Interface/Raptor/pull/38/commits/5ef6da09bd6151bb5f429828441fd046c6d9beff

**Pull request merged**
