### PR TITLE
Some cleaning for English language file and fixed German translation.

### PR DESCRIPTION
**Pull request by heuchi**
I've removed some empty lines from English and German translation files. (Hope that's fine)

Two keys appeared twice:
rated and uciAnalW_7
I assumed it's save to just delete the second "rated" line, because it's the same value.
uciAnalW_7, however, seems to be a typo the second time. Maybe you can check on that one.

There were also two new keys missing in the German file, which lead to error messages.

### CODE REVIEW

**Comment by heuchi** [comment]
Added a fall back mechanism to use English strings if a translation file is missing a key.
This allows to use the Italian translation, although it will not be complete.

One more question:
It looks like the Messages_*.properties files contain some unused keys from former program versions. Do you think we should try to remove those unused keys?

**Comment by cday-fics** [comment]
I am sure there is a lot that needs to be cleaned up. Feel free to remove the unused keys and clean up as needed. If I ever add back that functionality I will likely change the GUI completely and have new labels.

**Comment by cday-fics** [comment]
Started working on all of the action name/descriptions. Still have a lot of these to go.
I also started adding all the translations missing at the top of the resource bundle files.

**Comment by heuchi** [comment]
About removing unused translation strings:
I tried to create a tool to find these, but since some code, which is no longer used is still in the source tree it cannot find all unneeded strings, because it cannot possibly try to find out if a certain piece of code is ever executed.

So my question is: 
Would you consider removing files like raptor/src/raptor/pref/page/ConnectorQuadrantsPage.java?
Or could you provide me with a list of those files, so I could temporarily rename them here, to make my tool work more efficiently?

**Comment by cday-fics** [comment]
I just removed that and RaptorWindowQuadrantsPage. If you find any other dead code feel free to delete it. If it is ever needed in the future one can grab it from source control.

**Pull request merged**
